# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='number_of_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
