# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_auto_20160630_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='budget',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='trippoint',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='trippoint',
            name='next_point',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.TripPoint'),
        ),
    ]
