# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_auto_20160630_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.Destination')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='plan',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Destination'),
        ),
    ]
