# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name_plural': 'agencies'},
        ),
        migrations.AddField(
            model_name='destination',
            name='district',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tour.District'),
            preserve_default=False,
        ),
    ]
