# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_auto_20160701_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippoint',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
