# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0011_trippoint_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trippoint',
            name='name',
        ),
    ]
