# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_remove_trippoint_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='text',
        ),
    ]
