# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0014_auto_20160702_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='number_of_days',
            field=models.IntegerField(default=0),
        ),
    ]
