# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0015_auto_20160702_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='starting_point',
            new_name='next_point',
        ),
    ]
